-- ══════════════════════════════════════════════════════════════════════════════
-- ⚡ DOGAR SAJJI RMS — FULL SUPABASE POSTGRESQL SCHEMA & INITIAL DATA
-- ══════════════════════════════════════════════════════════════════════════════
-- Instructions:
-- 1. Create a free project on https://supabase.com
-- 2. Open SQL Editor in your Supabase Dashboard
-- 3. Copy & paste this entire SQL script and click "RUN"
-- 4. Copy your Supabase Project URL and Anon Key into the app under "☁️ Cloud DB"
-- ══════════════════════════════════════════════════════════════════════════════

-- 1. MENU CATEGORIES
CREATE TABLE IF NOT EXISTS public.menu_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

-- 2. MENU ITEMS
CREATE TABLE IF NOT EXISTS public.menu_items (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL,
  cat TEXT,
  price NUMERIC DEFAULT 0,
  discount NUMERIC DEFAULT 0,
  desc_text TEXT DEFAULT '',
  img TEXT DEFAULT '',
  available BOOLEAN DEFAULT true,
  variants JSONB DEFAULT '[]'::jsonb
);

-- 3. DEALS
CREATE TABLE IF NOT EXISTS public.deals (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT,
  items JSONB DEFAULT '[]'::jsonb,
  price NUMERIC DEFAULT 0,
  available BOOLEAN DEFAULT true
);

-- 4. TABLES
CREATE TABLE IF NOT EXISTS public.tables (
  id BIGINT PRIMARY KEY,
  status TEXT DEFAULT 'available',
  persons INT DEFAULT 0,
  seats INT DEFAULT 4,
  reserved_for TEXT DEFAULT '',
  reserved_time TEXT DEFAULT ''
);

-- 5. ORDERS
CREATE TABLE IF NOT EXISTS public.orders (
  id TEXT PRIMARY KEY,
  table_id BIGINT,
  items JSONB DEFAULT '[]'::jsonb,
  status TEXT DEFAULT 'pending',
  note TEXT DEFAULT '',
  time TEXT,
  waiter TEXT,
  is_add_on BOOLEAN DEFAULT false,
  total NUMERIC DEFAULT 0,
  order_type TEXT DEFAULT 'Dine-in',
  customer_phone TEXT DEFAULT '',
  customer_address TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. UNPAID BILLS
CREATE TABLE IF NOT EXISTS public.unpaid_bills (
  bill_key TEXT PRIMARY KEY,
  order_id TEXT,
  items JSONB DEFAULT '[]'::jsonb,
  time TEXT,
  add_on_tickets INT DEFAULT 0
);

-- 7. INVENTORY
CREATE TABLE IF NOT EXISTS public.inventory (
  id BIGINT PRIMARY KEY,
  item TEXT NOT NULL,
  unit TEXT,
  stock NUMERIC DEFAULT 0,
  min NUMERIC DEFAULT 0,
  price NUMERIC DEFAULT 0,
  last TEXT
);

-- 8. EMPLOYEES
CREATE TABLE IF NOT EXISTS public.employees (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL,
  cnic TEXT DEFAULT '',
  phone TEXT DEFAULT '',
  designation TEXT DEFAULT '',
  salary NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'Present',
  address TEXT DEFAULT '',
  salary_payments JSONB DEFAULT '[]'::jsonb,
  advances JSONB DEFAULT '[]'::jsonb,
  attendance_log JSONB DEFAULT '[]'::jsonb
);

-- 9. PETTY CASH
CREATE TABLE IF NOT EXISTS public.petty_cash (
  id BIGINT PRIMARY KEY,
  name TEXT,
  category TEXT,
  amount NUMERIC DEFAULT 0,
  date TEXT,
  notes TEXT DEFAULT '',
  closed INT DEFAULT 0,
  closeout_id TEXT DEFAULT ''
);

-- 10. SALES LEDGER
CREATE TABLE IF NOT EXISTS public.sales_ledger (
  id TEXT PRIMARY KEY,
  date TEXT,
  table_id BIGINT,
  items JSONB DEFAULT '[]'::jsonb,
  total NUMERIC DEFAULT 0,
  payment TEXT,
  waiter TEXT,
  discount NUMERIC DEFAULT 0,
  per_head NUMERIC DEFAULT 0,
  order_type TEXT DEFAULT 'Dine-in',
  customer_phone TEXT DEFAULT '',
  customer_address TEXT DEFAULT '',
  closed INT DEFAULT 0,
  closeout_id TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. EXPENSE LEDGER
CREATE TABLE IF NOT EXISTS public.expense_ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date TEXT,
  category TEXT,
  amount NUMERIC DEFAULT 0,
  description TEXT DEFAULT '',
  meta JSONB DEFAULT '{}'::jsonb
);

-- 12. SETTINGS
CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value JSONB DEFAULT '{}'::jsonb
);

-- 13. APP USERS
CREATE TABLE IF NOT EXISTS public.app_users (
  username TEXT PRIMARY KEY,
  password TEXT NOT NULL,
  role TEXT DEFAULT 'Admin',
  name TEXT DEFAULT ''
);

-- 14. CANCELLED ORDERS
CREATE TABLE IF NOT EXISTS public.cancelled_orders (
  id TEXT PRIMARY KEY,
  date TEXT,
  time TEXT,
  order_id TEXT,
  table_id INTEGER,
  order_type TEXT DEFAULT 'Dine-in',
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  cost NUMERIC DEFAULT 0,
  waiter TEXT DEFAULT '',
  cancel_type TEXT DEFAULT 'Partial',
  closed INT DEFAULT 0,
  closeout_id TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 15. DAILY CLOSEOUTS
CREATE TABLE IF NOT EXISTS public.daily_closeouts (
  id TEXT PRIMARY KEY,
  date TEXT,
  time TEXT,
  total_sales NUMERIC DEFAULT 0,
  sales_count INT DEFAULT 0,
  total_expenses NUMERIC DEFAULT 0,
  total_profit NUMERIC DEFAULT 0,
  total_cancelled_cost NUMERIC DEFAULT 0,
  cancelled_count INT DEFAULT 0,
  closed_by TEXT DEFAULT '',
  timestamp BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ══════════════════════════════════════════════════════════════════════════════
-- SEED INITIAL DATA FOR DOGAR SAJJI & RESTAURANT
-- ══════════════════════════════════════════════════════════════════════════════

-- Seed Tables (1 to 12)
INSERT INTO public.tables (id, status, persons, seats) VALUES
  (1, 'available', 0, 4), (2, 'available', 0, 4), (3, 'available', 0, 4), (4, 'available', 0, 4),
  (5, 'available', 0, 4), (6, 'available', 0, 4), (7, 'available', 0, 4), (8, 'available', 0, 4),
  (9, 'available', 0, 4), (10, 'available', 0, 4), (11, 'available', 0, 4), (12, 'available', 0, 4)
ON CONFLICT (id) DO NOTHING;

-- Seed Categories
INSERT INTO public.menu_categories (name) VALUES
  ('Sajji With Rice (چاول کے ساتھ)'),
  ('Sajji Without Rice (چاول کے بغیر)'),
  ('Rice Sides (چاول)'),
  ('Raita & Salads (رائتہ)'),
  ('Cold Drinks & Water (کولڈ ڈرنکس)')
ON CONFLICT (name) DO NOTHING;

-- Seed Menu Items
INSERT INTO public.menu_items (id, name, cat, price, discount, desc_text, img, available, variants) VALUES
  (1, 'Full Sajji with Rice (فل سجی باچاول)', 'Sajji With Rice (چاول کے ساتھ)', 1950, 0, 'Delicious full roasted chicken sajji served with aromatic rice', 'assets/items/sajji_rice.jpg', true, '[]'::jsonb),
  (2, 'Half Sajji with Rice (ہاف سجی باچاول)', 'Sajji With Rice (چاول کے ساتھ)', 1050, 0, 'Half roasted chicken sajji served with aromatic rice', 'assets/items/sajji_rice.jpg', true, '[]'::jsonb),
  (3, 'Quarter Sajji with Rice (کوارٹر سجی باچاول)', 'Sajji With Rice (چاول کے ساتھ)', 600, 0, 'Quarter roasted chicken sajji served with aromatic rice', 'assets/items/sajji_rice.jpg', true, '[]'::jsonb),
  (4, 'Full Sajji without Rice (فل سجی بغیر چاول)', 'Sajji Without Rice (چاول کے بغیر)', 1600, 0, 'Traditional full roasted chicken sajji', 'assets/items/sajji_chicken.jpg', true, '[]'::jsonb),
  (5, 'Half Sajji without Rice (ہاف سجی بغیر چاول)', 'Sajji Without Rice (چاول کے بغیر)', 800, 0, 'Traditional half roasted chicken sajji', 'assets/items/sajji_chicken.jpg', true, '[]'::jsonb),
  (6, 'Quarter Sajji without Rice (کوارٹر سجی بغیر چاول)', 'Sajji Without Rice (چاول کے بغیر)', 400, 0, 'Traditional quarter roasted chicken sajji', 'assets/items/sajji_chicken.jpg', true, '[]'::jsonb),
  (7, 'Full Rice (فل چاول)', 'Rice Sides (چاول)', 400, 0, 'Full portion of specially seasoned sajji rice', 'assets/items/rice_side.jpg', true, '[]'::jsonb),
  (8, 'Half Rice (ہاف چاول)', 'Rice Sides (چاول)', 250, 0, 'Half portion of specially seasoned sajji rice', 'assets/items/rice_side.jpg', true, '[]'::jsonb),
  (9, 'Fresh Raita (رائتہ)', 'Raita & Salads (رائتہ)', 70, 0, 'Fresh mint & zeera raita', 'assets/items/raita.jpg', true, '[]'::jsonb),
  (10, 'Half Mineral Water (ہاف واٹر)', 'Cold Drinks & Water (کولڈ ڈرنکس)', 60, 0, '500ml Mineral Water', 'assets/items/drinks.jpg', true, '[]'::jsonb),
  (11, 'Full Mineral Water (فل واٹر)', 'Cold Drinks & Water (کولڈ ڈرنکس)', 120, 0, '1.5 Liter Mineral Water', 'assets/items/drinks.jpg', true, '[]'::jsonb),
  (12, 'Drink (1.5 Liter)', 'Cold Drinks & Water (کولڈ ڈرنکس)', 210, 0, '1.5 Liter Chilled Soft Drink', 'assets/items/drinks.jpg', true, '[]'::jsonb),
  (13, 'Drink (1 Liter)', 'Cold Drinks & Water (کولڈ ڈرنکس)', 170, 0, '1.0 Liter Chilled Soft Drink', 'assets/items/drinks.jpg', true, '[]'::jsonb),
  (14, 'Drink (NR Regular)', 'Cold Drinks & Water (کولڈ ڈرنکس)', 80, 0, 'Regular NR Chilled Beverage', 'assets/items/drinks.jpg', true, '[]'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, cat = EXCLUDED.cat, price = EXCLUDED.price,
  desc_text = EXCLUDED.desc_text, img = EXCLUDED.img, available = EXCLUDED.available;

-- Seed Deals
INSERT INTO public.deals (id, name, category, items, price, available) VALUES
  (1, 'Full Sajji Deal with Rice & Raita', 'Special Sajji Deals', '["1x Full Sajji with Rice", "1x Fresh Raita"]'::jsonb, 2020, true),
  (2, 'Half Sajji Deal with Rice & Raita', 'Special Sajji Deals', '["1x Half Sajji with Rice", "1x Fresh Raita"]'::jsonb, 1120, true)
ON CONFLICT (id) DO NOTHING;

-- Seed App Users
INSERT INTO public.app_users (username, password, role, name) VALUES
  ('admin', '1234', 'Admin', 'Master Admin / Manager'),
  ('order1', '1234', 'Order Taker', 'Order Taker 1'),
  ('order2', '1234', 'Order Taker', 'Order Taker 2')
ON CONFLICT (username) DO NOTHING;

-- ══════════════════════════════════════════════════════════════════════════════
-- ENABLE ROW LEVEL SECURITY & OPEN POLICIES (for public web/POS access)
-- ══════════════════════════════════════════════════════════════════════════════

ALTER TABLE public.menu_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unpaid_bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.petty_cash ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expense_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cancelled_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_closeouts ENABLE ROW LEVEL SECURITY;

-- Allow full access to anon/public users
DO $$ 
DECLARE
  t text;
BEGIN
  FOR t IN SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' LOOP
    EXECUTE format('DROP POLICY IF EXISTS "Public Full Access" ON public.%I', t);
    EXECUTE format('CREATE POLICY "Public Full Access" ON public.%I FOR ALL USING (true) WITH CHECK (true)', t);
  END LOOP;
END $$;

-- Enable Realtime Sync (Idempotent: adds tables safely without duplicate_object error)
DO $$
DECLARE
  tbl_name text;
  tables_to_add text[] := ARRAY[
    'orders', 'tables', 'unpaid_bills', 'menu_items', 
    'menu_categories', 'deals', 'inventory', 'employees', 
    'petty_cash', 'sales_ledger', 'expense_ledger', 'settings', 
    'app_users', 'cancelled_orders', 'daily_closeouts'
  ];
BEGIN
  FOREACH tbl_name IN ARRAY tables_to_add LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_publication_tables 
      WHERE pubname = 'supabase_realtime' 
      AND schemaname = 'public' 
      AND tablename = tbl_name
    ) THEN
      BEGIN
        EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I', tbl_name);
      EXCEPTION WHEN duplicate_object THEN
        NULL;
      END;
    END IF;
  END LOOP;
END $$;

-- ══════════════════════════════════════════════════════════════════════════════
-- SAFE RETROFIT MIGRATION FOR PREVIOUSLY CREATED SUPABASE TABLES
-- ══════════════════════════════════════════════════════════════════════════════
ALTER TABLE IF EXISTS public.petty_cash ADD COLUMN IF NOT EXISTS closed INT DEFAULT 0;
ALTER TABLE IF EXISTS public.petty_cash ADD COLUMN IF NOT EXISTS closeout_id TEXT DEFAULT '';

ALTER TABLE IF EXISTS public.sales_ledger ADD COLUMN IF NOT EXISTS closed INT DEFAULT 0;
ALTER TABLE IF EXISTS public.sales_ledger ADD COLUMN IF NOT EXISTS closeout_id TEXT DEFAULT '';

ALTER TABLE IF EXISTS public.cancelled_orders ADD COLUMN IF NOT EXISTS closed INT DEFAULT 0;
ALTER TABLE IF EXISTS public.cancelled_orders ADD COLUMN IF NOT EXISTS closeout_id TEXT DEFAULT '';

